Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/18/2022
Var
// Seção de Declarações das variáveis 
   msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   msg <- "Olá, Mundo!"
   Escreva(msg)

Fimalgoritmo
